[profile.default]
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
test = "contracts/test"
cache_path = "contracts/cache_forge"
solc = "0.8.20"
via_ir = true
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/=contracts/lib/openzeppelin-contracts/",
  "forge-std/=contracts/lib/forge-std/src/",
  "ds-test/=contracts/lib/forge-std/lib/ds-test/src/"
]

[fmt]
line_length = 120
